name: playbox
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  sizer: ^2.0.15
  flutter_svg: ^2.0.5
  email_validator: ^2.1.17
  dropdown_button2: ^2.1.4
  flutter_conditional_rendering: ^2.0.0
  dio: ^5.2.1+1
  get_storage: ^2.1.1
  fluttertoast: ^8.2.2
  json_annotation: ^4.8.1
  build_runner: ^2.3.3
  json_serializable: ^6.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/logo/
    - assets/icons/

  fonts:
    - family: Jakarta
      fonts:
        - asset: assets/fonts/Plus_Jakarta_Sans/PlusJakartaSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Plus_Jakarta_Sans/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: assets/fonts/Plus_Jakarta_Sans/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/Plus_Jakarta_Sans/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/Plus_Jakarta_Sans/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Plus_Jakarta_Sans/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/Plus_Jakarta_Sans/PlusJakartaSans-ExtraBold.ttf
          weight: 800
